name: dineros
description: A Very Good Project created by Very Good CLI.
version: 1.0.1+3
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  adaptive_theme: ^3.6.0
  bloc: ^8.1.2
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  expenses:
    path: packages/expenses
  expenses_hive:
    path: packages/expenses_hive
  expenses_repository:
    path: packages/expenses_repository
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  formz: ^0.6.1
  intl: ^0.18.0
  pull_down_button: ^0.9.3

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
