name: expenses_hive
description: A flutter package implementing the expenses library
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  expenses:
    path: ../expenses
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  meta: ^1.10.0
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
